[project]
name = "retrofun"
version = "0.1.0"
description = "A dummy project made for learning SQLAlchemy 2"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.1.1",
    "sqlalchemy>=2.0.43",
]
