"""multi-language support

Revision ID: f068e2daa468
Revises: 8524fdc70cdd
Create Date: 2026-01-21 07:46:02.399098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f068e2daa468'
down_revision: Union[str, Sequence[str], None] = '8524fdc70cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=32), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_languages'))
                    )
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_languages_name'), [
                              'name'], unique=True)

    with op.batch_alter_table('blog_articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translation_of_id',
                            sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column('language_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_blog_articles_language_id'), [
                              'language_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_articles_translation_of_id'), [
                              'translation_of_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f(
            'fk_blog_articles_language_id_languages'), 'languages', ['language_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f(
            'fk_blog_articles_translation_of_id_blog_articles'), 'blog_articles', ['translation_of_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_articles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f(
            'fk_blog_articles_translation_of_id_blog_articles'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f(
            'fk_blog_articles_language_id_languages'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_blog_articles_translation_of_id'))
        batch_op.drop_index(batch_op.f('ix_blog_articles_language_id'))
        batch_op.drop_column('language_id')
        batch_op.drop_column('translation_of_id')

    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_languages_name'))

    op.drop_table('languages')
    # ### end Alembic commands ###
